// almost entirely directly copied from winit (https://github.com/rust-windowing/winit/blob/master/src/event.rs)
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Key {
    /// The '1' key over the letters.
    Key1,
    /// The '2' key over the letters.
    Key2,
    /// The '3' key over the letters.
    Key3,
    /// The '4' key over the letters.
    Key4,
    /// The '5' key over the letters.
    Key5,
    /// The '6' key over the letters.
    Key6,
    /// The '7' key over the letters.
    Key7,
    /// The '8' key over the letters.
    Key8,
    /// The '9' key over the letters.
    Key9,
    /// The '0' key over the 'O' and 'P' keys.
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    /// The Escape key, next to F1.
    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    /// Print Screen/SysRq.
    Snapshot,
    /// Scroll Lock.
    Scroll,
    /// Pause/Break key, next to Scroll lock.
    Pause,

    /// `Insert`, next to Backspace.
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,

    Left,
    Up,
    Right,
    Down,

    /// The Backspace key, right over Enter.
    Backspace,
    /// The Enter key.
    Return,
    /// The space bar.
    Space,

    /// The "Compose" key on Linux.
    Compose,

    Caret,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadDivide,
    NumpadDecimal,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    NumpadMultiply,
    NumpadSubtract,

    AbntC1,
    AbntC2,
    Apostrophe,
    Apps,
    Asterisk,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Mute,
    MyComputer,
    // also called "Next"
    NavigateForward,
    // also called "Prior"
    NavigateBackward,
    NextTrack,
    NoConvert,
    OEM102,
    Period,
    PlayPause,
    Plus,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

#[cfg(feature = "winit")]
impl From<winit::event::VirtualKeyCode> for Key {
    #[inline]
    fn from(key: winit::event::VirtualKeyCode) -> Self {
        use winit::event::VirtualKeyCode as KeyCode;

        match key {
            KeyCode::Key1 => Key::Key1,
            KeyCode::Key2 => Key::Key2,
            KeyCode::Key3 => Key::Key3,
            KeyCode::Key4 => Key::Key4,
            KeyCode::Key5 => Key::Key5,
            KeyCode::Key6 => Key::Key6,
            KeyCode::Key7 => Key::Key7,
            KeyCode::Key8 => Key::Key8,
            KeyCode::Key9 => Key::Key9,
            KeyCode::Key0 => Key::Key0,
            KeyCode::A => Key::A,
            KeyCode::B => Key::B,
            KeyCode::C => Key::C,
            KeyCode::D => Key::D,
            KeyCode::E => Key::E,
            KeyCode::F => Key::F,
            KeyCode::G => Key::G,
            KeyCode::H => Key::H,
            KeyCode::I => Key::I,
            KeyCode::J => Key::J,
            KeyCode::K => Key::K,
            KeyCode::L => Key::L,
            KeyCode::M => Key::M,
            KeyCode::N => Key::N,
            KeyCode::O => Key::O,
            KeyCode::P => Key::P,
            KeyCode::Q => Key::Q,
            KeyCode::R => Key::R,
            KeyCode::S => Key::S,
            KeyCode::T => Key::T,
            KeyCode::U => Key::U,
            KeyCode::V => Key::V,
            KeyCode::W => Key::W,
            KeyCode::X => Key::X,
            KeyCode::Y => Key::Y,
            KeyCode::Z => Key::Z,
            KeyCode::Escape => Key::Escape,
            KeyCode::F1 => Key::F1,
            KeyCode::F2 => Key::F2,
            KeyCode::F3 => Key::F3,
            KeyCode::F4 => Key::F4,
            KeyCode::F5 => Key::F5,
            KeyCode::F6 => Key::F6,
            KeyCode::F7 => Key::F7,
            KeyCode::F8 => Key::F8,
            KeyCode::F9 => Key::F9,
            KeyCode::F10 => Key::F10,
            KeyCode::F11 => Key::F11,
            KeyCode::F12 => Key::F12,
            KeyCode::F13 => Key::F13,
            KeyCode::F14 => Key::F14,
            KeyCode::F15 => Key::F15,
            KeyCode::F16 => Key::F16,
            KeyCode::F17 => Key::F17,
            KeyCode::F18 => Key::F18,
            KeyCode::F19 => Key::F19,
            KeyCode::F20 => Key::F20,
            KeyCode::F21 => Key::F21,
            KeyCode::F22 => Key::F22,
            KeyCode::F23 => Key::F23,
            KeyCode::F24 => Key::F24,
            KeyCode::Snapshot => Key::Snapshot,
            KeyCode::Scroll => Key::Scroll,
            KeyCode::Pause => Key::Pause,
            KeyCode::Insert => Key::Insert,
            KeyCode::Home => Key::Home,
            KeyCode::Delete => Key::Delete,
            KeyCode::End => Key::End,
            KeyCode::PageDown => Key::PageDown,
            KeyCode::PageUp => Key::PageUp,
            KeyCode::Left => Key::Left,
            KeyCode::Up => Key::Up,
            KeyCode::Right => Key::Right,
            KeyCode::Down => Key::Down,
            KeyCode::Back => Key::Backspace,
            KeyCode::Return => Key::Return,
            KeyCode::Space => Key::Space,
            KeyCode::Compose => Key::Compose,
            KeyCode::Caret => Key::Caret,
            KeyCode::Numlock => Key::Numlock,
            KeyCode::Numpad0 => Key::Numpad0,
            KeyCode::Numpad1 => Key::Numpad1,
            KeyCode::Numpad2 => Key::Numpad2,
            KeyCode::Numpad3 => Key::Numpad3,
            KeyCode::Numpad4 => Key::Numpad4,
            KeyCode::Numpad5 => Key::Numpad5,
            KeyCode::Numpad6 => Key::Numpad6,
            KeyCode::Numpad7 => Key::Numpad7,
            KeyCode::Numpad8 => Key::Numpad8,
            KeyCode::Numpad9 => Key::Numpad9,
            KeyCode::NumpadAdd => Key::NumpadAdd,
            KeyCode::NumpadDivide => Key::NumpadDivide,
            KeyCode::NumpadDecimal => Key::NumpadDecimal,
            KeyCode::NumpadComma => Key::NumpadComma,
            KeyCode::NumpadEnter => Key::NumpadEnter,
            KeyCode::NumpadEquals => Key::NumpadEquals,
            KeyCode::NumpadMultiply => Key::NumpadMultiply,
            KeyCode::NumpadSubtract => Key::NumpadSubtract,
            KeyCode::AbntC1 => Key::AbntC1,
            KeyCode::AbntC2 => Key::AbntC2,
            KeyCode::Apostrophe => Key::Apostrophe,
            KeyCode::Apps => Key::Apps,
            KeyCode::Asterisk => Key::Asterisk,
            KeyCode::At => Key::At,
            KeyCode::Ax => Key::Ax,
            KeyCode::Backslash => Key::Backslash,
            KeyCode::Calculator => Key::Calculator,
            KeyCode::Capital => Key::Capital,
            KeyCode::Colon => Key::Colon,
            KeyCode::Comma => Key::Comma,
            KeyCode::Convert => Key::Convert,
            KeyCode::Equals => Key::Equals,
            KeyCode::Grave => Key::Grave,
            KeyCode::Kana => Key::Kana,
            KeyCode::Kanji => Key::Kanji,
            KeyCode::LAlt => Key::LAlt,
            KeyCode::LBracket => Key::LBracket,
            KeyCode::LControl => Key::LControl,
            KeyCode::LShift => Key::LShift,
            KeyCode::LWin => Key::LWin,
            KeyCode::Mail => Key::Mail,
            KeyCode::MediaSelect => Key::MediaSelect,
            KeyCode::MediaStop => Key::MediaStop,
            KeyCode::Minus => Key::Minus,
            KeyCode::Mute => Key::Mute,
            KeyCode::MyComputer => Key::MyComputer,
            KeyCode::NavigateForward => Key::NavigateForward,
            KeyCode::NavigateBackward => Key::NavigateBackward,
            KeyCode::NextTrack => Key::NextTrack,
            KeyCode::NoConvert => Key::NoConvert,
            KeyCode::OEM102 => Key::OEM102,
            KeyCode::Period => Key::Period,
            KeyCode::PlayPause => Key::PlayPause,
            KeyCode::Plus => Key::Plus,
            KeyCode::Power => Key::Power,
            KeyCode::PrevTrack => Key::PrevTrack,
            KeyCode::RAlt => Key::RAlt,
            KeyCode::RBracket => Key::RBracket,
            KeyCode::RControl => Key::RControl,
            KeyCode::RShift => Key::RShift,
            KeyCode::RWin => Key::RWin,
            KeyCode::Semicolon => Key::Semicolon,
            KeyCode::Slash => Key::Slash,
            KeyCode::Sleep => Key::Sleep,
            KeyCode::Stop => Key::Stop,
            KeyCode::Sysrq => Key::Sysrq,
            KeyCode::Tab => Key::Tab,
            KeyCode::Underline => Key::Underline,
            KeyCode::Unlabeled => Key::Unlabeled,
            KeyCode::VolumeDown => Key::VolumeDown,
            KeyCode::VolumeUp => Key::VolumeUp,
            KeyCode::Wake => Key::Wake,
            KeyCode::WebBack => Key::WebBack,
            KeyCode::WebFavorites => Key::WebFavorites,
            KeyCode::WebForward => Key::WebForward,
            KeyCode::WebHome => Key::WebHome,
            KeyCode::WebRefresh => Key::WebRefresh,
            KeyCode::WebSearch => Key::WebSearch,
            KeyCode::WebStop => Key::WebStop,
            KeyCode::Yen => Key::Yen,
            KeyCode::Copy => Key::Copy,
            KeyCode::Paste => Key::Paste,
            KeyCode::Cut => Key::Cut,
        }
    }
}
